/**
 * 
 * MPDC Collector API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TwitterSampleSuperQueryInfo } from './twitterSampleSuperQueryInfo';
import { TwitterTweetSuperQueryInfo } from './twitterTweetSuperQueryInfo';


export interface ListTwitterQueryResponse { 
    tweetSuperQueries: Array<TwitterTweetSuperQueryInfo>;
    sampleSuperQueries: Array<TwitterSampleSuperQueryInfo>;
}

