/**
 * 
 * MPDC Collector API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QueryState { 
    streamStatus: QueryState.StreamStatusEnum;
    statusText: string;
    lastCheckpointTimestamp?: string;
    lastProcessingTimestamp: string;
    id?: number;
}
export namespace QueryState {
    export type StreamStatusEnum = 'NEW' | 'WAITING' | 'STARTING' | 'RUNNING' | 'DONE' | 'INTERRUPTED' | 'ABORTED' | 'ERROR_INTERRUPT' | 'ERROR_ABORT' | 'RECOVERABLE' | 'UNRECOVERABLE' | 'RECOVERED';
    export const StreamStatusEnum = {
        New: 'NEW' as StreamStatusEnum,
        Waiting: 'WAITING' as StreamStatusEnum,
        Starting: 'STARTING' as StreamStatusEnum,
        Running: 'RUNNING' as StreamStatusEnum,
        Done: 'DONE' as StreamStatusEnum,
        Interrupted: 'INTERRUPTED' as StreamStatusEnum,
        Aborted: 'ABORTED' as StreamStatusEnum,
        ErrorInterrupt: 'ERROR_INTERRUPT' as StreamStatusEnum,
        ErrorAbort: 'ERROR_ABORT' as StreamStatusEnum,
        Recoverable: 'RECOVERABLE' as StreamStatusEnum,
        Unrecoverable: 'UNRECOVERABLE' as StreamStatusEnum,
        Recovered: 'RECOVERED' as StreamStatusEnum
    };
}


