/**
 * 
 * MPDC Collector API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubQueryStats { 
    numPosts: number;
    numAuthorStatuses: number;
    numTotalMediaObjects: number;
    numProcessedMediaObjects: number;
    numUniqueMediaObjects: number;
    numRemainingMediaObjects: number;
}

