/**
 * 
 * MPDC Collector API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TwitterSampleSubQueryInfo } from './twitterSampleSubQueryInfo';
import { QueryData } from './queryData';
import { TwitterSampleQueryOptions } from './twitterSampleQueryOptions';


export interface TwitterSampleSuperQueryInfo { 
    queryData: QueryData;
    sampleQueryData: TwitterSampleQueryOptions;
    fetchMultimedia: Array<TwitterSampleSuperQueryInfo.FetchMultimediaEnum>;
    indexInCineast: boolean;
    subQueries: Array<TwitterSampleSubQueryInfo>;
    id: number;
}
export namespace TwitterSampleSuperQueryInfo {
    export type FetchMultimediaEnum = 'UNKNOWN' | 'ANIMATED_IMAGE' | 'IMAGE' | 'VIDEO';
    export const FetchMultimediaEnum = {
        Unknown: 'UNKNOWN' as FetchMultimediaEnum,
        AnimatedImage: 'ANIMATED_IMAGE' as FetchMultimediaEnum,
        Image: 'IMAGE' as FetchMultimediaEnum,
        Video: 'VIDEO' as FetchMultimediaEnum
    };
}


