/**
 * 
 * MPDC Collector API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TwitterTweetQueryOptions } from './twitterTweetQueryOptions';
import { QueryData } from './queryData';
import { TwitterTweetSubQueryInfo } from './twitterTweetSubQueryInfo';


export interface TwitterTweetSuperQueryInfo { 
    queryData: QueryData;
    tweetQueryData: TwitterTweetQueryOptions;
    fetchMultimedia: Array<TwitterTweetSuperQueryInfo.FetchMultimediaEnum>;
    indexInCineast: boolean;
    subQueries: Array<TwitterTweetSubQueryInfo>;
    id: number;
}
export namespace TwitterTweetSuperQueryInfo {
    export type FetchMultimediaEnum = 'UNKNOWN' | 'ANIMATED_IMAGE' | 'IMAGE' | 'VIDEO';
    export const FetchMultimediaEnum = {
        Unknown: 'UNKNOWN' as FetchMultimediaEnum,
        AnimatedImage: 'ANIMATED_IMAGE' as FetchMultimediaEnum,
        Image: 'IMAGE' as FetchMultimediaEnum,
        Video: 'VIDEO' as FetchMultimediaEnum
    };
}


