/**
 * 
 * MPDC Collector API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QueryData } from './queryData';
import { QueryState } from './queryState';
import { SubQueryStats } from './subQueryStats';
import { TwitterSampleQueryOptions } from './twitterSampleQueryOptions';


export interface TwitterSampleSubQueryInfo { 
    apiKey: string;
    temporalType: TwitterSampleSubQueryInfo.TemporalTypeEnum;
    queryData: QueryData;
    sampleQueryData: TwitterSampleQueryOptions;
    state: QueryState;
    stats: SubQueryStats;
    id: number;
    percentComplete: number;
}
export namespace TwitterSampleSubQueryInfo {
    export type TemporalTypeEnum = 'SEARCH' | 'STREAM';
    export const TemporalTypeEnum = {
        Search: 'SEARCH' as TemporalTypeEnum,
        Stream: 'STREAM' as TemporalTypeEnum
    };
}


